/**
 * exportUtils.js — PDF / CSV 내보내기 유틸리티
 *
 * 추가 패키지 없이 브라우저 내장 기능을 활용합니다.
 * - PDF: window.print() 기반 (인쇄 대화상자에서 "PDF로 저장" 선택)
 * - CSV: Blob 다운로드
 */

/**
 * 특정 DOM 영역을 프린트 전용 레이아웃으로 PDF 출력 대화상자를 엽니다.
 * @param {string} elementId     - 출력할 DOM 요소의 id
 * @param {string} documentTitle - PDF 파일명에 사용될 제목
 */
export function printElementAsPdf(elementId, documentTitle = 'NetSphere Report') {
  const el = document.getElementById(elementId);
  if (!el) {
    console.warn(`[exportUtils] Element #${elementId} not found`);
    return;
  }

  const printWindow = window.open('', '_blank', 'width=900,height=700');
  if (!printWindow) {
    console.warn('[exportUtils] Popup blocked — allow popups for PDF export');
    return;
  }

  const styles = Array.from(document.querySelectorAll('link[rel="stylesheet"], style'))
    .map(node => node.outerHTML)
    .join('\n');

  printWindow.document.write(`
    <!DOCTYPE html>
    <html class="${document.documentElement.className}">
    <head>
      <meta charset="UTF-8" />
      <title>${documentTitle}</title>
      ${styles}
      <style>
        @media print {
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
        body {
          font-family: 'Inter', sans-serif;
          padding: 24px;
          background: white !important;
          color: #0f172a !important;
        }
        .no-print { display: none !important; }
      </style>
    </head>
    <body>
      <div style="margin-bottom:16px;border-bottom:2px solid #e2e8f0;padding-bottom:12px;">
        <h1 style="font-size:20px;font-weight:800;color:#1e293b;margin:0;">
          ${documentTitle}
        </h1>
        <p style="font-size:11px;color:#64748b;margin-top:4px;">
          Generated by NetSphere • ${new Date().toLocaleString()}
        </p>
      </div>
      ${el.innerHTML}
    </body>
    </html>
  `);
  printWindow.document.close();

  // 스타일이 로드된 후 인쇄 다이얼로그 표시
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.focus();
      printWindow.print();
    }, 400);
  };
}

/**
 * 2차원 데이터를 CSV 파일로 다운로드합니다.
 * @param {Array<Array<string>>} rows   - [header, ...dataRows]
 * @param {string}               filename
 */
export function downloadCsv(rows, filename = 'netsphere-export.csv') {
  if (!rows || rows.length === 0) return;

  const escape = (val) => {
    const s = String(val ?? '');
    return s.includes(',') || s.includes('"') || s.includes('\n')
      ? `"${s.replace(/"/g, '""')}"`
      : s;
  };

  const csv = rows.map(row => row.map(escape).join(',')).join('\n');
  const bom = '\uFEFF'; // BOM for Excel Korean support
  const blob = new Blob([bom + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * 객체 배열 → CSV 다운로드 편의 함수
 * @param {Array<Object>} data
 * @param {string[]}      columns  - 출력할 키 목록
 * @param {string[]}      headers  - 컬럼 한국어 제목 (columns와 동일 길이)
 * @param {string}        filename
 */
export function exportObjectsToCsv(data, columns, headers, filename = 'netsphere-export.csv') {
  if (!data || data.length === 0) return;
  const rows = [
    headers || columns,
    ...data.map(item => columns.map(col => item[col] ?? '')),
  ];
  downloadCsv(rows, filename);
}
