#!/usr/bin/env python3
from __future__ import annotations

import argparse
import shutil
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile


DEFAULT_DOCS = [
    "docs/INSTALL_UPGRADE_RECOVERY_RUNBOOK.md",
    "docs/RELEASE_GATE_RUNBOOK.md",
    "docs/BRANCH_PROTECTION_CHECKLIST.md",
    "docs/VENDOR_SUPPORT_POLICY.md",
    "docs/LICENSE_SIGNING.md",
    "docs/operational-validation/REAL_DEVICE_ACCEPTANCE_RUNBOOK.md",
]


def _copy_docs(project_root: Path, out_dir: Path, docs: list[str]) -> list[Path]:
    copied: list[Path] = []
    for rel in docs:
        src = (project_root / rel).resolve()
        if not src.exists():
            continue
        dst = out_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        copied.append(dst)
    return copied


def main() -> int:
    parser = argparse.ArgumentParser(description="Package NetSphere operational runbooks into a distributable bundle.")
    parser.add_argument("--out-dir", default="dist/runbook-package", help="Output directory for copied docs")
    parser.add_argument(
        "--zip-name",
        default="runbook-package.zip",
        help="Zip filename generated under --out-dir parent",
    )
    parser.add_argument(
        "--doc",
        action="append",
        default=[],
        help="Additional doc path(s) to include (project-relative). Repeatable.",
    )
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parents[2]
    out_dir = (project_root / args.out_dir).resolve()
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    docs = list(DEFAULT_DOCS)
    docs.extend(str(x).strip() for x in (args.doc or []) if str(x).strip())
    copied = _copy_docs(project_root, out_dir, docs)

    manifest = out_dir / "MANIFEST.txt"
    manifest.write_text(
        "\n".join(
            [
                "NetSphere Runbook Package",
                "=========================",
                "",
                "Included files:",
                *[str(p.relative_to(out_dir)) for p in copied],
                "",
                "Generated by: Netsphere_Free_Backend/tools/package_runbooks.py",
            ]
        ),
        encoding="utf-8",
    )

    zip_path = out_dir.parent / str(args.zip_name or "runbook-package.zip").strip()
    with ZipFile(zip_path, "w", compression=ZIP_DEFLATED) as zf:
        for path in copied + [manifest]:
            zf.write(path, arcname=str(path.relative_to(out_dir)))

    print(f"Packaged {len(copied)} docs to {out_dir}")
    print(f"Zip: {zip_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
